### ISSUE TITLE
Vevo Global Search Does Not Work

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/Vevo.bundle#6]
The json URL (http://api.vevo.com/mobile/v1/lookahead.json?q=%s&fullItems=true&newSearch=yes) no longer works and returns a service deprecated message. 

The website json is https://apiv2.vevo.com/search?query=&token= and requires a session token.

**Comment by sander1** [comment]
Fixed with 0fa2ea064d892cf66c64abf267dc47ca6a97daa8 and 1d8a7b42a1020f695b2d42f130a3407e142a16f5.
